name: Test Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -e .[docs]

      - name: Test with unittest
        run: python -m unittest discover -s tests